### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by sebie** [Elundris/Air-Classic#1]
Heya,

Stumbled on this repo from your profile and saw that it had a blank wiki. 

I can finish of the Wiki if you want, check todo and add stuff if you want.

Additionally I can create one for the new skin if you wish.

Best of luck,

@sebie

-

*(Dark theme :+1:)*

**Comment by Elundris** [comment]
By all means, please do!

Most of the documentation for Air Classic won't be changing. As for the current Air, the only thing I would mention is that I tend to use the Steam community group as the information hub for now. I absolutely don't mind useful info making it's way over to Github as well, I'm just not sure where this would fit into the long term plans.

I'd be curious to see how the wiki handles the FAQ's... since I'm not too happy with having it as a discussion on the Steam group. I've been toying around with the idea of hosting it on the website as well, just to make it easier to read and organize. But - seeing this, it might be easier to manage here instead.

Just thinking out loud.. But thank you for the offer, and if you have the time to help out it would be greatly appreciated! :D

**Comment by sebie** [comment]
In my opinion this is easier to manage. If you want you can give me the questions and answers for the FAQ and I can do that.

Can you enable a Wiki on the new skin please, so I can create a FAQ there?

And no problem at all. It lets me contribute to something I enjoy and use.

**Comment by Elundris** [comment]
Whoops, didn't know it was disabled! Should be on now. :)

Here's the current FAQ: http://steamcommunity.com/groups/airforsteam/discussions/1/619568793939735236/

**Comment by sebie** [comment]
Thank you!

Now this how I thought of it currently.
-
Home page
  * You know, a home page. Links to everything else related. 

FAQ
  * FAQ. Most likly in the format shown in Air Classic Wiki.

That's all :P

**Comment by sebie** [comment]
But if you want, I could update slowly the GAQ on Steam if that is better?

**Comment by Elundris** [comment]
Here would probably be a better place for the FAQ than Steam just due to the better handling of styles and markdown (this is just my assumption though).

I would say the main page is airforsteam.com, but in the end I try to funnel everyone to the Steam group since you have the ability to ask questions and be vocal there.

**Comment by sebie** [comment]
No, it's fine. I will put the info here as well, but in my opinion it wouldn't be bad to get more people involded in the GitHub side of it. Issues and checking through. Instead of on Steam?

And just playing around with a Steam test group.

**Comment by sebie** [comment]
Take a look at the Wiki for the new skin. (All pages would be great). Feedback, opinions and thoughts would be appreciated.

**Comment by Elundris** [comment]
Let's chat on Steam so we can formulate a game plan. My main concern is making sure we don't duplicate any work.

My thoughts so far:

1. FAQ will probably be better on the wiki than on Steam.

2. Utilizing the issues on Github might be a better idea. Worth discussing as I can try to point people here.

3. The main reason I was avoiding using the .md files was because people were getting confused trying to open them in notepad.

4. I personally thought using the Releases page as the changelog was more useful since you can download past versions as well as browse the changes: https://github.com/Elundris/Air-for-Steam/releases

I would still point people to the Community group as the main hub for Air though.

**Comment by sebie** [comment]
1. Agreed. I woul dsay it is mostly due to Steam formatting limitations.
  a) So does that mean on Steam there would be just a link to the FAQ here on GitHub?
  b) Currently on the Wiki, is that how you would like it to look? The FAQ.
2. Ok.

3. Tbh, I think that a Readme is a must it is the front page of the repo and you can state in caps or bold etc that `.md` are just documentation. And you don't have to include them in the releases :wink: .

4. Sure if releases work better then lets use them.
 
5. Awesome!

I would say that this serves for devs, people who register, and for maintain it easily.

**Comment by Elundris** [comment]
1. a) Yep. b) I messed around with it a bit here: https://github.com/Elundris/Air-for-Steam/wiki/FAQ

2. 

3. Is there a way to have it not be included when someone downloads a release without me having to upload a manual zip just to delete it?

I concur!

**Comment by sebie** [comment]
1 b) That is actually nice. What I would say is that because you can link directly to them (https://github.com/Elundris/Air-for-Steam/wiki/FAQ#installation-instructions-windows) we could have a bunch of links to individual questions.

Yes, because the Steam hub is mostly for *gamers* if you will and from my perspective they have been asking good and resonable questions. But, GitHub is for devs, like I said. For people to create PR's, so I would think it could be more complex.

Still, I would just put links as said above on the Wiki here, and copy them to the Steam group. So then people getredirected to the question they specifically need.

3. Reading through various [GitHub](https://help.github.com/articles/creating-releases/) resources about it. Lemme try something.

**Comment by Elundris** [comment]
Sounds like a plan. I think the only thing I'd say we shouldn't do is link to each question individually. While that would be useful, I think I'd rather just link people directly here for the FAQ vs having them look through questions on Steam and then come here after that. Saves a step for them and makes it easier to upkeep for us (for when new questions are added/updated, etc).

**Comment by sebie** [comment]
Yeah, that would make sense. But keeping in mind that; most important and most asked at the top, gradually to less important. And then atthe end. Questions from contributers, guide what to submit, what not to.

**Comment by Elundris** [comment]
Closing since we obviously already have the ball rolling at this point!

**Comment by sebie** [comment]
Yeah makes sense, but you also need the feeling that you are closing down issues. :)

(Doing what I can to help around).

**Comment by Elundris** [comment]
For sure man, and thank you very much for everything! It really helps to keep these threads contained and organized. :)
